### ISSUE TITLE
debug switch bad with nodemon

### ISSUE THREAD

**Issue by TLKG** [bdspen/nodemon_vscode#2]
Windows 7. Have nodemon installed locally, followed exactly the same creating my launch.json.
  nodemon  --debug server.js 
got:
[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node --debug server.js`
(node:13132) [DEP0062] DeprecationWarning: `node --debug` and `node --debug-brk`
 are invalid. Please use `node --inspect` or `node --inspect-brk` instead.
[nodemon] app crashed - waiting for file changes before starting...

Replace it with the following works!
  nodemon --inspect server.js
However attach getting:
Error, cannot connec to runtime process (reason: This socket has been ended by the other party).
Debug Console shows:
  Debugging with legacy protocol because Node.js version could not be determined.

**Comment by bdspen** [comment]
@TLKG which node version are you using? Doesn't the --inspect flag give you a link to open in chrome to view the console?

here is what I get when I use --inspect instead of --debug:

`Warning: This is an experimental feature and could change at any time.
To start debugging, open the following URL in Chrome:
    chrome-devtools://devtools/remote/serve_file/@60cd6e859b9f557d2312f5bf532f6aec5f284980/inspector.html?experiments=true&v8only=true&ws=localhost:9229/b44b5379-c1bb-4295-a843-148d460ca64f`

**Comment by don78colorado** [comment]
@TLKG I had that problem as well and I fixed it by specifying a port.  
`nodemon --inspect=5858 server.js`
It seems like it doesn't default and you need to specify a port.  That port needs to match your @code configuration.
@bdspen I believe newer versions of node uses --inspect instead of --debug.  The message you're getting might be from an older version.  Thanks for this tutorial!

**Comment by bdspen** [comment]
You are correct, in fact this is how I run nodemon now....

`nodemon --inspect server.js PORT=5000`

or `node --inspect server.js PORT=5000` for running node.

and my vs code settings:

`        {
            "name": "attach",
            "type": "node",
            "request": "attach",
            "protocol": "inspector",
            "port": 9229,
            "restart": true,
            "localRoot": "${workspaceRoot}"
        }`

you will get a devtools link to debug your application in chrome if you want to as well  like:
`chrome-devtools://devtools/remote/serve_file/@60cd6e859b9f557d2312f5bf532f6aec5f284980/inspector.html?experiments=true&v8only=true&ws=localhost:9229/06fb8962-539e-41e8-9607-e1ff2de322f5`

**Comment by dchege711** [comment]
Remove the `localRoot` entry: https://github.com/Microsoft/vscode/issues/65742
